consult_knowledge_base:
  description: >
    Retrieve and summarize company-specific standards, policies, and tools for {task}
    from the organization's knowledge base. Strict adherence to company guidelines is mandatory.
  expected_output: >
    Concise summary of applicable company standards, policies, and tools, with exact
    references. No deviations from official guidelines are permitted.
  agent: cloud_engineer

research_best_practices:
  description: >
    If necessary, conduct additional research on industry best practices and latest
    developments related to {task}, ensuring alignment with organizational policies.
  expected_output: >
    A report on industry best practices and recent developments, highlighting how they
    align with or complement the organization's existing standards.
  agent: software_engineer

create_implementation_plan:
  description: >
    Based on the knowledge base findings and additional research, create a concise
    implementation plan and instruction list for {task}.
  expected_output: >
    A step-by-step implementation plan and instruction list, tailored to the organization's
    standards and incorporating industry best practices.
  agent: cloud_engineer

generate_startup_template:
  description: >
    Create a task-specific startup template based on the implementation plan and
    organizational standards. The format should be appropriate for {task}, which may
    include code (e.g., Terraform, python, typesctipt e.t.c), configuration files, or text instructions.
  expected_output: >
    A well-documented, organization-compliant startup template tailored to {task}.
    This could be code, configuration, or detailed text instructions, as appropriate
    for the specific task requirements.
  agent: software_engineer

review_and_optimize:
  description: >
    Review the implementation plan and startup template for potential optimizations,
    security enhancements, and alignment with machine learning best practices if applicable.
  expected_output: >
    A detailed review report with specific recommendations for optimizations, security
    improvements, and ML-specific considerations where relevant.
  agent: machine_learning_engineer
