pool:
  vmImage: ubuntu-latest

trigger: none

parameters:
  - name: deploymentEnvironment
    displayName: Deployment Environment
    type: string
    default: poc1
    values:
      - poc1
      - development
      - sit
      - production
  - name: isInitialRelease # Indicates whether this is the initial release of the ingestion node
    displayName: Is Initial Release?
    type: boolean
    default: false
  - name: databaseName # Name of the Snowflake Database
    displayName: Database Name
    type: string
  - name: databaseSchemaName # Name of the schema in the aforementioned Snowflake DB
    displayName: Database Schema Name
    type: string

resources:
  repositories:
    - repository: templates
      type: git
      name: CORE.Utilities/Pipeline.Templates

variables:
  armServiceConnectionEndpoint: Azure Resource Manager endpoint # Name of the Azure Resource Manager endpoint
  keyVaultName: <key_vault_name> # Name of the key vault from which to download secrets
  keyVaultRgName: <key_vault_resource_group_name> # Name of the resource group in which the key vault is provisioned
  containerRegistry: <container_registry> # Name of the container registry in which the ingestion node image is hosted
  workingDirectory: <path_to_ingestion_node> # Path to the directory in the repo that contains the ingestion node
  nodeDisplayName: <node_display_name> # Used to label jobs in Azure DevOps pipeline
  meshnodeName: <meshnode_name>
  snowflakeRole: <snowflake_role> # Role for executing SnowSQL scripts
  snowflakeWarehouse: <snowflake_warehouse>

stages:
  - template: dbt-nodes/release.yml@templates
    parameters:
      isInitialRelease: ${{ parameters.isInitialRelease }}
      snowflakeDatabaseName: ${{ parameters.databaseName }}
      snowflakeDatabaseSchemaName: ${{ parameters.databaseSchemaName }}

